
name: Build Pipeline

on:
  push:
    tags: ["v*.*.*"]

env:
  IMAGE_NAME:           ${{ secrets.image_name }}
  subscription_id:      ${{ secrets.subscription_id }}
  client_id:            ${{ secrets.client_id }}
  client_secret:        ${{ secrets.client_secret }}
  tenant_id:            ${{ secrets.tenant_id }}
  container_registry:   ${{ secrets.container_registry }}  #Example: myregistry.azurecr.io


jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.container_registry }}
          username: ${{ env.client_id }} 
          password: ${{ env.client_secret }} 

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}